Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/11/2024
Var
min, calorias: inteiro;
funcao caloriasKickboxing(soma: inteiro): inteiro;
inicio
soma:=min*10
fimfuncao
Inicio
escreval("Informe o tempo em minutos que você treina")
leia(min)
calorias:=caloriasKickboxing()
escreval("Você queimou", calorias, "calorias")


Fimalgoritmo