Algoritmo "semnome"
// Disciplina   : [Desenvolver Algoritmos]
// Professor   : Jefferson Vinícios da Fonseca e Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/10/2024
Var
numero,resultado: real;

Inicio
escreval("digite um numero em metros para converter para cetimetros", numero)
leia(numero)

resultado:=numero*1000
escreval("O resultado e", resultado)

Fimalgoritmo