Algoritmo "Soma e Impressão"
// Disciplina   : [Desenvolver Algoritmos]
// Professor   : Jefferson Vinícios da Fonseca e Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/10/2024
Var
numero, numero2,resultado: real;

Inicio
escreval("digite o numero:", numero)
leia (numero)


escreval("digite o numero:", numero2)
leia (numero2)

resultado:= numero+numero2

escreval("resultado e:", resultado)









Fimalgoritmo